# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Everything
version:      0.2
version_from: lib/Acme/Everything.pm
installdirs:  site
requires:
    Class::Autouse:                1.03
    CPANPLUS:                      0
    File::Spec:                    0.83
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
