abstract: Effectively loads every class in CPAN
author: 'Adam Kennedy <cpan@ali.as>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Acme-Everything
no_index:
  directory:
    - inc
    - t
requires:
  CPANPLUS: 0
  Class::AutoUse: 1.03
  perl: 5.6.0
version: 1.00
